In [1]:
import numpy as np
import pandas as pd

In [7]:
np.random.seed(17)   ## for reproducibility
n = 20
num = np.arange(1, n+1)
num[-2] = num[-3]    ## duplicates (replace 19 with 18)
print(num)
print(num[-2])
print(num[-8])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 18 20]
18
13


#### 1. For generating random names for given list.

In [8]:
names_list = ["Harpreet", "Riya", "Ayra", "Zuraiz", "Rahul", "Babita", "Romaila"]
names = np.random.choice(names_list, n)
print(names)

['Riya' 'Romaila' 'Romaila' 'Riya' 'Harpreet' 'Babita' 'Romaila' 'Rahul'
 'Rahul' 'Rahul' 'Riya' 'Romaila' 'Riya' 'Riya' 'Harpreet' 'Ayra' 'Ayra'
 'Zuraiz' 'Romaila' 'Zuraiz']


#### 2. For generating random age 

In [10]:
age_list = (19, 21, 27, 20, 28, 26, 31, 30)
age = np.random.choice(age_list, n)
print(age)
## age_list = np.random.randint(19, 35, size = n)
## age_list

[30 31 27 27 21 19 21 19 19 28 28 26 30 27 28 28 26 20 20 20]


#### 3. For generating random gender using p variable

In [11]:
gender = np.random.choice(["M", "F", np.nan], size = n, p = [0.50, 0.45, 0.05])
gender

array(['F', 'F', 'F', 'F', 'M', 'F', 'F', 'F', 'M', 'M', 'M', 'F', 'M',
       'M', 'nan', 'M', 'F', 'F', 'nan', 'M'], dtype='<U32')

#### 4. Generating age with randint and as type function

In [15]:
age_list = np.random.randint(19, 35, size = n).astype(float)
age_list[[1,6]] = np.nan
age = age_list
age

array([30., nan, 28., 21., 32., 32., nan, 19., 21., 28., 31., 29., 31.,
       20., 27., 20., 19., 24., 24., 25.])

#### 5. Generating salary with randint and astype function. 

In [23]:
salary_list = np.random.randint(21000, 55000, size = n).astype(float)
age_list[[2,8]] = np.nan
salary = salary_list
salary

array([46953., 22897., 40037., 30390., 34510., 51263., 38690., 41751.,
       50948., 36784., 49791., 32916., 22011., 43195., 29060., 50706.,
       29730., 31971., 48776., 52645.])

#### 6. Generating dataframe

In [24]:
id = list(range(1, len(names)+ 1))
data = pd.DataFrame({"Id" : id, "Name": names, "Age": age, "Gender": gender, "Salary": salary})
data

,Id,Name,Age,Gender,Salary
0,1,Riya,30.0,F,46953.0
1,2,Romaila,NaN,F,22897.0
2,3,Romaila,NaN,F,40037.0
3,4,Riya,21.0,F,30390.0
4,5,Harpreet,32.0,M,34510.0
5,6,Babita,32.0,F,51263.0
6,7,Romaila,NaN,F,38690.0
7,8,Rahul,19.0,F,41751.0
8,9,Rahul,NaN,M,50948.0
9,10,Rahul,28.0,M,36784.0
